// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatIsTheNextDayOffOrWorkDay.Repository.Context;

namespace WhatIsTheNextDayOffOrWorkDay.Repository.Migrations
{
    [DbContext(typeof(WhatIsTheNextDayOffOrWorkDayDbContext))]
    [Migration("20201111235439_db_11_WhatIsTheNextDayOffOrWorkDay")]
    partial class db_11_WhatIsTheNextDayOffOrWorkDay
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("VigenciaInicial")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apelido")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Sequencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<int>("Indicador")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.ToTable("Sequencias");
                });

            modelBuilder.Entity("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Pessoa", b =>
                {
                    b.HasOne("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Escala", "Escala")
                        .WithMany("Pessoas")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");
                });

            modelBuilder.Entity("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Sequencia", b =>
                {
                    b.HasOne("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Escala", "Escala")
                        .WithMany("Sequencias")
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");
                });

            modelBuilder.Entity("WhatIsTheNextDayOffOrWorkDay.Domain.Entity.Escala", b =>
                {
                    b.Navigation("Pessoas");

                    b.Navigation("Sequencias");
                });
#pragma warning restore 612, 618
        }
    }
}
